recipe_sha: 6b5c8b3490665c9e89e4970602a5708a45cf48fd67f39441fd2140d067918dd3  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |2-
    MACS2/Prob.c:1538:32: error: '_PyCFrame' has no member named 'use_tracing'
     1538 |      (unlikely((tstate)->cframe->use_tracing) &&\
          |                                ^~
    MACS2/Prob.c:981:43: note: in definition of macro 'unlikely'
      981 |   #define unlikely(x) __builtin_expect(!!(x), 0)
          |                                           ^
    MACS2/Prob.c:1577:15: note: in expansion of macro '__Pyx_IsTracing'
     1577 |           if (__Pyx_IsTracing(tstate, 1, 1)) {\
          |               ^~~~~~~~~~~~~~~
    MACS2/Prob.c:11768:3: note: in expansion of macro '__Pyx_TraceCall'
    11768 |   __Pyx_TraceCall("__Pyx_PyMODINIT_FUNC PyInit_Prob(void)", __pyx_f[0], 1, 0, __PYX_ERR(0, 1, __pyx_L1_error));
          |   ^~~~~~~~~~~~~~~
    MACS2/Prob.c:1538:32: error: '_PyCFrame' has no member named 'use_tracing'
     1538 |      (unlikely((tstate)->cframe->use_tracing) &&\
          |                                ^~
    MACS2/Prob.c:981:43: note: in definition of macro 'unlikely'
      981 |   #define unlikely(x) __builtin_expect(!!(x), 0)
          |                                           ^
    MACS2/Prob.c:1585:11: note: in expansion of macro '__Pyx_IsTracing'
     1585 |       if (__Pyx_IsTracing(tstate, 1, 1)) {\
          |           ^~~~~~~~~~~~~~~
    MACS2/Prob.c:11768:3: note: in expansion of macro '__Pyx_TraceCall'
    11768 |   __Pyx_TraceCall("__Pyx_PyMODINIT_FUNC PyInit_Prob(void)", __pyx_f[0], 1, 0, __PYX_ERR(0, 1, __pyx_L1_error));
          |   ^~~~~~~~~~~~~~~
    MACS2/Prob.c:1538:32: error: '_PyCFrame' has no member named 'use_tracing'
     1538 |      (unlikely((tstate)->cframe->use_tracing) &&\
          |                                ^~
    MACS2/Prob.c:981:43: note: in definition of macro 'unlikely'
      981 |   #define unlikely(x) __builtin_expect(!!(x), 0)
          |                                           ^
    MACS2/Prob.c:1636:19: note: in expansion of macro '__Pyx_IsTracing'
     1636 |               if (__Pyx_IsTracing(tstate, 0, 0)) {\
          |                   ^~~~~~~~~~~~~~~
    MACS2/Prob.c:11898:3: note: in expansion of macro '__Pyx_TraceReturn'
    11898 |   __Pyx_TraceReturn(Py_None, 0);
          |   ^~~~~~~~~~~~~~~~~
    MACS2/Prob.c:1538:32: error: '_PyCFrame' has no member named 'use_tracing'
     1538 |      (unlikely((tstate)->cframe->use_tracing) &&\
          |                                ^~
    MACS2/Prob.c:981:43: note: in definition of macro 'unlikely'
      981 |   #define unlikely(x) __builtin_expect(!!(x), 0)
          |                                           ^
    MACS2/Prob.c:1643:15: note: in expansion of macro '__Pyx_IsTracing'
     1643 |           if (__Pyx_IsTracing(tstate, 0, 0)) {\
          |               ^~~~~~~~~~~~~~~
    MACS2/Prob.c:11898:3: note: in expansion of macro '__Pyx_TraceReturn'
    11898 |   __Pyx_TraceReturn(Py_None, 0);
          |   ^~~~~~~~~~~~~~~~~
    MACS2/Prob.c: In function '__Pyx_TraceSetupAndCall':
    MACS2/Prob.c:1538:32: error: '_PyCFrame' has no member named 'use_tracing'
     1538 |      (unlikely((tstate)->cframe->use_tracing) &&\
          |                                ^~
    MACS2/Prob.c:981:43: note: in definition of macro 'unlikely'
      981 |   #define unlikely(x) __builtin_expect(!!(x), 0)
          |                                           ^
    MACS2/Prob.c:12039:16: note: in expansion of macro '__Pyx_IsTracing'
    12039 |         return __Pyx_IsTracing(tstate, 0, 0) && retval;
          |                ^~~~~~~~~~~~~~~
    error: command '/opt/conda/conda-bld/macs2_1717624280245/_build_env/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1
    [1;31merror[0m: [1msubprocess-exited-with-error[0m

    [31m[0m [32mBuilding wheel for MACS2 [0m[1;32m([0m[32mpyproject.toml[0m[1;32m)[0m did not run successfully.
    [31m[0m exit code: [1;36m1[0m
    [31m>[0m See above for output.

    [1;35mnote[0m: This error originates from a subprocess, and is likely not a problem with pip.
    [1;35mfull command[0m: [34m/opt/conda/conda-bld/macs2_1717624280245/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python /opt/conda/conda-bld/macs2_1717624280245/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmpodigz2ng[0m
    [1;35mcwd[0m: /opt/conda/conda-bld/macs2_1717624280245/work
    Building wheel for MACS2 (pyproject.toml): finished with status 'error'
  [31m  ERROR: Failed building wheel for MACS2[0m[31m
  [0mFailed to build MACS2
  [31mERROR: Could not build wheels for MACS2, which is required to install pyproject.toml-based projects[0m[31m
  [0mException information:
  Traceback (most recent call last):
    File "$PREFIX/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
      status = run_func(*args)
               ^^^^^^^^^^^^^^^
    File "$PREFIX/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
      return func(self, options, args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "$PREFIX/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 429, in run
      raise InstallationError(
  pip._internal.exceptions.InstallationError: Could not build wheels for MACS2, which is required to install pyproject.toml-based projects
  Removed build tracker: '/tmp/pip-build-tracker-xxrop7yn'
  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3638, in build_tree
      packages_from_this = build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2506, in build
      utils.check_call_env(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 405, in check_call_env
      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 381, in _func_defaulting_env_to_os_environ
      raise subprocess.CalledProcessError(proc.returncode, _args)
  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/macs2_1717624280245/work/conda_build.sh']' returned non-zero exit status 1.
# Last 100 lines of the build log.
