recipe_sha: 3610267290d8b8f268cecd167798b74c17a9562b2602eef4cb956f4101920488  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |-
  2024-06-04T15:23:20 Subdir: noarch Gathering repodata
  2024-06-04T15:23:20 noarch Writing pre-patch repodata
  2024-06-04T15:23:20 noarch Applying patch instructions
  2024-06-04T15:23:20 noarch Writing patched repodata
  2024-06-04T15:23:20 noarch Building current_repodata subset
  2024-06-04T15:23:20 noarch Writing current_repodata subset
  2024-06-04T15:23:20 noarch Writing index HTML
  2024-06-04T15:23:21 Subdir: linux-64 Gathering repodata
  2024-06-04T15:23:21 linux-64 Writing pre-patch repodata
  2024-06-04T15:23:21 linux-64 Applying patch instructions
  2024-06-04T15:23:21 linux-64 Writing patched repodata
  2024-06-04T15:23:21 linux-64 Building current_repodata subset
  2024-06-04T15:23:21 linux-64 Writing current_repodata subset
  2024-06-04T15:23:21 linux-64 Writing index HTML
  2024-06-04T15:23:21 Subdir: linux-aarch64 Gathering repodata
  2024-06-04T15:23:21 linux-aarch64 Writing pre-patch repodata
  2024-06-04T15:23:21 linux-aarch64 Applying patch instructions
  2024-06-04T15:23:21 linux-aarch64 Writing patched repodata
  2024-06-04T15:23:21 linux-aarch64 Building current_repodata subset
  2024-06-04T15:23:21 linux-aarch64 Writing current_repodata subset
  2024-06-04T15:23:21 linux-aarch64 Writing index HTML
  2024-06-04T15:23:21 Subdir: noarch Gathering repodata
  2024-06-04T15:23:21 noarch Writing pre-patch repodata
  2024-06-04T15:23:21 noarch Applying patch instructions
  2024-06-04T15:23:21 noarch Writing patched repodata
  2024-06-04T15:23:21 noarch Building current_repodata subset
  2024-06-04T15:23:21 noarch Writing current_repodata subset
  2024-06-04T15:23:21 noarch Writing index HTML
  /opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py:501: UserWarning: RECIPE_PATH received is a file (/opt/recipe/meta.yaml).
  It should be a path to a folder.
  Forcing conda-build to use the recipe file.
    warnings.warn(
  WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
  Adding in variants from internal_defaults
  Adding in variants from /opt/host-conda-bld/conda_build_config_0_-e_conda_build_config.yaml
  Adding in variants from /opt/host-conda-bld/conda_build_config_1_-e_bioconda_utils-conda_build_config.yaml
  Attempting to finalize metadata for gimmemotifs-minimal
  Reloading output folder (file:///opt/host-conda-bld): ...working... done
  Getting pinned dependencies: ...working... done
  Reloading output folder (file:///opt/host-conda-bld): ...working... done
  Getting pinned dependencies: ...working... done
  Reloading output folder (file:///opt/host-conda-bld): ...working... done
  Getting pinned dependencies: ...working... done
  Reloading output folder (file:///opt/host-conda-bld): ...working... done
  Getting pinned dependencies: ...working... done
  Reloading output folder (file:///opt/host-conda-bld): ...working... done
  Getting pinned dependencies: ...working... done
  Reloading output folder (file:///opt/host-conda-bld): ...working... done
  Getting pinned dependencies: ...working... done
  Reloading output folder (file:///opt/host-conda-bld): ...working... done
  Getting pinned dependencies: ...working... done
  Reloading output folder (file:///opt/host-conda-bld): ...working... done
  Getting pinned dependencies: ...working... done
  Reloading output folder (file:///opt/host-conda-bld): ...working... done
  Getting pinned dependencies: ...working... done
  Reloading output folder (file:///opt/host-conda-bld): ...working... done
  Getting pinned dependencies: ...working... done
  Reloading output folder (file:///opt/host-conda-bld): ...working... done
  Getting pinned dependencies: ...working... done
  Attempting to finalize metadata for gimmemotifs
  BUILD START: ['gimmemotifs-minimal-0.18.0-py311h9f068be_6.tar.bz2', 'gimmemotifs-minimal-0.18.0-py39h0dd7abe_6.tar.bz2', 'gimmemotifs-minimal-0.18.0-py38hfe239e1_6.tar.bz2', 'gimmemotifs-minimal-0.18.0-py310hc31ed2c_6.tar.bz2', 'gimmemotifs-minimal-0.18.0-py312h719dbc0_6.tar.bz2', 'gimmemotifs-0.18.0-h9ee0642_6.tar.bz2']
  Reloading output folder (file:///opt/host-conda-bld): ...working... done
  Solving environment (_test_env): ...working... done
  Source cache directory is: /opt/conda/conda-bld/src_cache
  Downloading source to cache: gimmemotifs-0.18.0_8e7d23a898.tar.gz
  Downloading https://github.com/vanheeringen-lab/gimmemotifs/releases/download/0.18.0/gimmemotifs-0.18.0.tar.gz
  Traceback (most recent call last):
    File "/opt/conda/lib/python3.10/site-packages/conda/gateways/connection/download.py", line 128, in download_inner
      target.write(chunk)
  OSError: [Errno 28] No space left on device

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3638, in build_tree
      packages_from_this = build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2419, in build
      try_download(m, no_download_source=False, raise_error=True)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/render.py", line 762, in try_download
      source.provide(metadata)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/source.py", line 1035, in provide
      unpack(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/source.py", line 169, in unpack
      src_path, unhashed_fn = download_to_cache(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/source.py", line 103, in download_to_cache
      download(url, path)
    File "/opt/conda/lib/python3.10/site-packages/conda/common/io.py", line 86, in decorated
      return f(*args, **kwds)
    File "/opt/conda/lib/python3.10/site-packages/conda/gateways/connection/download.py", line 67, in download
      download_inner(
    File "/opt/conda/lib/python3.10/site-packages/conda/gateways/connection/download.py", line 131, in download_inner
      raise CondaError(message, target_path=target.name, errno=e.errno)
  conda.CondaError: Failed to write to /opt/conda/conda-bld/src_cache/gimmemotifs-0.18.0_8e7d23a898.tar.gz.partial
    errno: 28
# Last 100 lines of the build log.
