recipe_sha: 29c73c509dc94ef415931711eb85cb048bf4bf2a27c9f7ebe4fb9413d895dafc  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |2-
     INFO (mageck,bin/mageckGSEA): Needed DSO lib/libgcc_s.so.1 found in conda-forge/linux-64::libgcc-ng==13.2.0=h77fa898_7
     INFO (mageck,bin/mageckGSEA): Needed DSO x86_64-conda-linux-gnu/sysroot/lib64/libc.so.6 found in CDT/compiler package conda-forge/noarch::sysroot_linux-64==2.12=he073ed8_17
     INFO (mageck,bin/RRA): Needed DSO lib/libstdc.so.6 found in conda-forge/linux-64::libstdcxx-ng==13.2.0=hc0a3c3a_7
     INFO (mageck,bin/RRA): Needed DSO x86_64-conda-linux-gnu/sysroot/lib64/libm.so.6 found in CDT/compiler package conda-forge/noarch::sysroot_linux-64==2.12=he073ed8_17
     INFO (mageck,bin/RRA): Needed DSO lib/libgcc_s.so.1 found in conda-forge/linux-64::libgcc-ng==13.2.0=h77fa898_7
     INFO (mageck,bin/RRA): Needed DSO x86_64-conda-linux-gnu/sysroot/lib64/libc.so.6 found in CDT/compiler package conda-forge/noarch::sysroot_linux-64==2.12=he073ed8_17
     INFO (mageck): Interpreted package 'mageck' is interpreted by 'python'
  Fixing permissions
  INFO :: Time taken to mark (prefix)
          0 replacements in 0 files was 0.02 seconds
  Files containing CONDA_PREFIX
  -----------------------------
  bin/mageck (text): Patching
  TEST START: /opt/conda/conda-bld/linux-64/mageck-0.5.9.5-py310h84f13bb_5.tar.bz2
  Renaming work directory '/opt/conda/conda-bld/mageck_1717539229937/work' to '/opt/conda/conda-bld/mageck_1717539229937/work_moved_mageck-0.5.9.5-py310h84f13bb_5_linux-64'
  shutil.move(work)=/opt/conda/conda-bld/mageck_1717539229937/work, dest=/opt/conda/conda-bld/mageck_1717539229937/work_moved_mageck-0.5.9.5-py310h84f13bb_5_linux-64)
  Reloading output folder (local, file:///opt/host-conda-bld): ...working... done
  Solving environment (_test_env): ...working... done

  ## Package Plan ##

    environment location: /opt/conda/conda-bld/mageck_1717539229937/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p


  The following NEW packages will be INSTALLED:

      _libgcc_mutex:     0.1-conda_forge            conda-forge
      _openmp_mutex:     4.5-2_gnu                  conda-forge
      asttokens:         2.4.1-pyhd8ed1ab_0         conda-forge
      bzip2:             1.0.8-hd590300_5           conda-forge
      ca-certificates:   2024.6.2-hbcca054_0        conda-forge
      decorator:         5.1.1-pyhd8ed1ab_0         conda-forge
      exceptiongroup:    1.2.0-pyhd8ed1ab_2         conda-forge
      executing:         2.0.1-pyhd8ed1ab_0         conda-forge
      ipython:           8.25.0-pyh707e725_0        conda-forge
      jedi:              0.19.1-pyhd8ed1ab_0        conda-forge
      ld_impl_linux-64:  2.40-hf3520f5_2            conda-forge
      libblas:           3.9.0-22_linux64_openblas  conda-forge
      libcblas:          3.9.0-22_linux64_openblas  conda-forge
      libffi:            3.4.2-h7f98852_5           conda-forge
      libgcc-ng:         13.2.0-h77fa898_7          conda-forge
      libgfortran-ng:    13.2.0-h69a702a_7          conda-forge
      libgfortran5:      13.2.0-hca663fb_7          conda-forge
      libgomp:           13.2.0-h77fa898_7          conda-forge
      liblapack:         3.9.0-22_linux64_openblas  conda-forge
      libnsl:            2.0.1-hd590300_0           conda-forge
      libopenblas:       0.3.27-pthreads_h413a1c8_0 conda-forge
      libsqlite:         3.45.3-h2797004_0          conda-forge
      libstdcxx-ng:      13.2.0-hc0a3c3a_7          conda-forge
      libuuid:           2.38.1-h0b41bf4_0          conda-forge
      libxcrypt:         4.4.36-hd590300_1          conda-forge
      libzlib:           1.3.1-h4ab18f5_1           conda-forge
      mageck:            0.5.9.5-py310h84f13bb_5    local
      matplotlib-inline: 0.1.7-pyhd8ed1ab_0         conda-forge
      ncurses:           6.5-h59595ed_0             conda-forge
      numpy:             1.26.4-py310hb13e2d6_0     conda-forge
      openssl:           3.3.0-h4ab18f5_3           conda-forge
      parso:             0.8.4-pyhd8ed1ab_0         conda-forge
      pexpect:           4.9.0-pyhd8ed1ab_0         conda-forge
      pickleshare:       0.7.5-py_1003              conda-forge
      pip:               24.0-pyhd8ed1ab_0          conda-forge
      prompt-toolkit:    3.0.42-pyha770c72_0        conda-forge
      ptyprocess:        0.7.0-pyhd3deb0d_0         conda-forge
      pure_eval:         0.2.2-pyhd8ed1ab_0         conda-forge
      pygments:          2.18.0-pyhd8ed1ab_0        conda-forge
      python:            3.10.14-hd12c33a_0_cpython conda-forge
      python_abi:        3.10-4_cp310               conda-forge
      readline:          8.2-h8228510_1             conda-forge
      scipy:             1.13.1-py310h93e2701_0     conda-forge
      setuptools:        70.0.0-pyhd8ed1ab_0        conda-forge
      six:               1.16.0-pyh6c4a22f_0        conda-forge
      stack_data:        0.6.2-pyhd8ed1ab_0         conda-forge
      tk:                8.6.13-noxft_h4845f30_101  conda-forge
      traitlets:         5.14.3-pyhd8ed1ab_0        conda-forge
      typing_extensions: 4.12.1-pyha770c72_0        conda-forge
      tzdata:            2024a-h0c530f3_0           conda-forge
      wcwidth:           0.2.13-pyhd8ed1ab_0        conda-forge
      wheel:             0.43.0-pyhd8ed1ab_1        conda-forge
      xz:                5.2.6-h166bdaf_0           conda-forge

  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3653, in build_tree
      test(pkg, config=metadata.config.copy(), stats=stats)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3397, in test
      environ.create_env(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1049, in create_env
      _execute_actions(prefix, precs)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1332, in _execute_actions
      progressive_fetch_extract.execute()
    File "/opt/conda/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 891, in execute
      raise CondaMultiError(not_cancelled)
  conda.CondaMultiError: Error with archive /opt/conda/pkgs/scipy-1.13.1-py310h93e2701_0.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
# Last 100 lines of the build log.
