recipe_sha: 3b9c9c32cfa6f079ff37cd0f52fd8cf077f4cac6464b5a6ed5208ee3f70ca95a  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |-
  2024-06-04T15:13:21 noarch Building current_repodata subset
  2024-06-04T15:13:21 noarch Writing current_repodata subset
  2024-06-04T15:13:21 noarch Writing index HTML
  /opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py:501: UserWarning: RECIPE_PATH received is a file (/opt/recipe/meta.yaml).
  It should be a path to a folder.
  Forcing conda-build to use the recipe file.
    warnings.warn(
  WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
  Adding in variants from internal_defaults
  Adding in variants from /opt/host-conda-bld/conda_build_config_0_-e_conda_build_config.yaml
  Adding in variants from /opt/host-conda-bld/conda_build_config_1_-e_bioconda_utils-conda_build_config.yaml
  Attempting to finalize metadata for physlr
  Reloading output folder (file:///opt/host-conda-bld): ...working... done
  Getting pinned dependencies: ...working... done
  Reloading output folder (file:///opt/host-conda-bld): ...working... done
  Getting pinned dependencies: ...working... done
  Reloading output folder (file:///opt/host-conda-bld): ...working... done
  Getting pinned dependencies: ...working... done
  BUILD START: ['physlr-1.0.4-py39h4ac6f70_6.tar.bz2']
  Reloading output folder (file:///opt/host-conda-bld): ...working... done
  Solving environment (_h_env): ...working... done

  ## Package Plan ##

    environment location: /opt/conda/conda-bld/physlr_1717514002522/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh


  The following NEW packages will be INSTALLED:

      _libgcc_mutex:    0.1-conda_forge           conda-forge
      _openmp_mutex:    4.5-2_gnu                 conda-forge
      boost-cpp:        1.85.0-h44aadfe_1         conda-forge
      bzip2:            1.0.8-hd590300_5          conda-forge
      ca-certificates:  2024.6.2-hbcca054_0       conda-forge
      expat:            2.6.2-h59595ed_0          conda-forge
      gdbm:             1.18-h0a1914f_2           conda-forge
      icu:              73.2-h59595ed_0           conda-forge
      libboost:         1.85.0-hba137d9_1         conda-forge
      libboost-devel:   1.85.0-h00ab1b0_1         conda-forge
      libboost-headers: 1.85.0-ha770c72_1         conda-forge
      libexpat:         2.6.2-h59595ed_0          conda-forge
      libffi:           3.4.2-h7f98852_5          conda-forge
      libgcc-ng:        13.2.0-h77fa898_7         conda-forge
      libgomp:          13.2.0-h77fa898_7         conda-forge
      libsqlite:        3.45.3-h2797004_0         conda-forge
      libstdcxx-ng:     13.2.0-hc0a3c3a_7         conda-forge
      libxcb:           1.15-h0b41bf4_0           conda-forge
      libzlib:          1.3.1-h4ab18f5_1          conda-forge
      ncurses:          6.5-h59595ed_0            conda-forge
      openssl:          3.3.0-h4ab18f5_3          conda-forge
      pip:              24.0-pyhd8ed1ab_0         conda-forge
      pthread-stubs:    0.4-h36c2ea0_1001         conda-forge
      pypy:             7.3.15-1_pypy39           conda-forge
      pypy3.9:          7.3.15-h9557127_1         conda-forge
      python:           3.9.18-1_73_pypy          conda-forge
      python_abi:       3.9-4_pypy39_pp73         conda-forge
      readline:         8.2-h8228510_1            conda-forge
      setuptools:       70.0.0-pyhd8ed1ab_0       conda-forge
      sqlite:           3.45.3-h2c6b66d_0         conda-forge
      tk:               8.6.13-noxft_h4845f30_101 conda-forge
      tzdata:           2024a-h0c530f3_0          conda-forge
      wheel:            0.43.0-pyhd8ed1ab_1       conda-forge
      xorg-kbproto:     1.0.7-h7f98852_1002       conda-forge
      xorg-libx11:      1.8.9-h8ee46fc_0          conda-forge
      xorg-libxau:      1.0.11-hd590300_0         conda-forge
      xorg-libxdmcp:    1.1.3-h7f98852_0          conda-forge
      xorg-xextproto:   7.3.0-h0b41bf4_1003       conda-forge
      xorg-xproto:      7.0.31-h7f98852_1007      conda-forge
      xz:               5.2.6-h166bdaf_0          conda-forge
      zlib:             1.3.1-h4ab18f5_1          conda-forge
      zstd:             1.5.6-ha6fb4c9_0          conda-forge

  Preparing transaction: ...working... done
  Verifying transaction: ...working... done
  Executing transaction: ...working... done
  ERROR conda.core.link:_execute(950): An error occurred while installing package 'conda-forge::icu-73.2-h59595ed_0'.
  Rolling back transaction: ...working... done
  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3638, in build_tree
      packages_from_this = build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2409, in build
      create_build_envs(top_level_pkg, notest)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2183, in create_build_envs
      environ.create_env(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1049, in create_env
      _execute_actions(prefix, precs)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1334, in _execute_actions
      unlink_link_transaction.execute()
    File "/opt/conda/lib/python3.10/site-packages/conda/core/link.py", line 354, in execute
      self._execute(
    File "/opt/conda/lib/python3.10/site-packages/conda/core/link.py", line 970, in _execute
      raise CondaMultiError(
  conda.CondaMultiError: [Errno 28] No space left on device
  ()
# Last 100 lines of the build log.
